### ISSUE TITLE
update mongodb dep to 1.4.31

### ISSUE THREAD

**Issue by drulia** [gordonmleigh/promised-mongo#16]
Currently it is using 1.4.0 and it is unable to authorize connection to v3 mongodb server, if you update dependeny to 1.4.31 it logs in without a problems.

P.S.
Worth mentioning that when trying to install current promised-mongo with node v0.12 it spews a lot of errors while trying to install 1.4.0 version of mongodb (problems with bson), but installing 1.4.31 seem to be working well. Maybe that's what is making the difference when authenticating.

**Comment by gordonmleigh** [comment]
This is now available in version 0.12.  Sorry for the delay.
