### ISSUE TITLE
Runtime warning: Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by kevin-qiu** [gordonmleigh/promised-mongo#18]
I get this warning everytime I load the library. `Failed to load c++ bson extension, using pure JS version`. There aren't any other errors or anything, but I'm afraid that the pure JS version of the bson extension would be slower in performance. Any ideas as to why I might be getting this issue?

Great library btw.

**Comment by rnikoopour** [comment]
Hey Kevin:  Are you running on OS X?  I'm getting the same error and was wondering if it is OS specific or not.

**Comment by leonkyr** [comment]
I use MacOS

**Comment by git-jiby-me** [comment]
This happens if you install this module on an OS / nodeJS / ioJS version and try to run the module from another OS / nodeJS / ioJS version. The reason is BSON is compiled natively and uses node sources for this, and if node version is different than the one on which the native binary was compiled it wont load.

**Comment by hveiras** [comment]
I can confirm this issue is not related with promised-mongo. I stil did not install it and I have the bson error.

**Comment by git-jiby-me** [comment]
@hveiras yes, you are right, comes from bson library which is a dependency of mongodb native driver as well as this one.

**Comment by gordonmleigh** [comment]
This is an issue with the bson library as already pointed out.  Check that the native module is being compiled when you install the package - make sure your platform is supported and you have the build tools installed.
