### ISSUE TITLE
Index weights are not being applied

### ISSUE THREAD

**Issue by StJohn3D** [gordonmleigh/promised-mongo#22]
Here is my code:
```
return db.assets.createIndex(
                {
                  name: "text",
                  tags: "text",
                },
                {
                  default_language: "english",
                  weights         : {
                                      name: 10,
                                      tags: 5,
                                    },
                  name            : "AssetTextSearch"
                }
              );
```

The resulting weights for _name_ and _tags_ are both 1
![screenshot 2015-06-24 09 53 49](https://cloud.githubusercontent.com/assets/7581439/8331611/46e9a7de-1a57-11e5-803d-1a07b8e2614b.png)

**Comment by gordonmleigh** [comment]
I can't repro this - see my latest commit which adds a test for this case.  Clone the repo, run `npm install` then run `mocha --grep "full text"` to confirm this.

What versions of node/mongo are you running?

**Comment by gordonmleigh** [comment]
I should also ask, what version of promised-mongo are you using?

**Comment by StJohn3D** [comment]
I am unable to run the tests.  Here is the error:

~/Desktop/test_Mongo/promised-mongo
[14:40:55]
> $ mocha --grep "full text"
[±master]
/Users/sjpeaster/Desktop/test_Mongo/promised-mongo/test/Collection.js:1
(function (exports, require, module, __filename, __dirname) { import
{expect}
                   
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles
(/usr/local/lib/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous>
(/usr/local/lib/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Thanks,
St. John

From:  Gordon Mackenzie-Leigh <notifications@github.com>
Reply-To:  gordonmleigh/promised-mongo
<reply+0073aeff0e541e1dd40f36f8ae8fce36fb3ead8cfa96729d92cf0000000111a2823e9
2a169ce0567b69c@reply.github.com>
Date:  Wednesday, June 24, 2015 at 10:35 AM
To:  gordonmleigh/promised-mongo <promised-mongo@noreply.github.com>
Cc:  "St. John Peaster" <stjohn3d@outlook.com>
Subject:  Re: [promised-mongo] Index weights are not being applied (#22)

mocha --grep "full text"

**Comment by StJohn3D** [comment]
Hi,
We are using 2.10.1

From:  Gordon Mackenzie-Leigh <notifications@github.com>
Reply-To:  gordonmleigh/promised-mongo
<reply+0073aeff6c2d8c54520fa5df63a8a0ae1051f2331be5710792cf0000000111a2849b9
2a169ce0567b69c@reply.github.com>
Date:  Wednesday, June 24, 2015 at 10:45 AM
To:  gordonmleigh/promised-mongo <promised-mongo@noreply.github.com>
Cc:  "St. John Peaster" <stjohn3d@outlook.com>
Subject:  Re: [promised-mongo] Index weights are not being applied (#22)


I should also ask, what version of promised-mongo are you using?


Reply to this email directly or view it on GitHub
<https://github.com/gordonmleigh/promised-mongo/issues/22#issuecomment-11489
4645> .

**Comment by gordonmleigh** [comment]
For tests you should run

    mocha --compilers js:babel/register --grep "full text"

Sorry I forgot the extra `compilers` option because I have it aliased.

As for versions - that doesn't look like the version of any of mongo, nodejs or promised-mongo, could you tell me the versions you are using for each of these?

**Comment by StJohn3D** [comment]
No worries.

Ok, versions
Nodejs: v0.12.4
mongodb: ^2.0.31
Promised-mongo: ^0.11.1

Tets results:
$ mocha --compilers js:babel/register --grep "full text"
[±master]


  Collection
    createIndex
      1) "before each" hook: callee$1$0


  0 passing (2s)
  1 failing

  1) Collection "before each" hook: callee$1$0:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being
called in this test.


Looks like the tests need a database running somewhere?

From:  Gordon Mackenzie-Leigh <notifications@github.com>
Reply-To:  gordonmleigh/promised-mongo
<reply+0073aeff5c6d00c5ed2cb6ee6a28ac5985f4e03c2c1e336392cf0000000111a35f2b9
2a169ce0567b69c@reply.github.com>
Date:  Thursday, June 25, 2015 at 2:18 AM
To:  gordonmleigh/promised-mongo <promised-mongo@noreply.github.com>
Cc:  "St. John Peaster" <stjohn3d@outlook.com>
Subject:  Re: [promised-mongo] Index weights are not being applied (#22)


For tests you should run
mocha --compilers js:babel/register --grep "full text"
Sorry I forgot the extra compilers option because I have it aliased.

As for versions - that doesn't look like the version of any of mongo, nodejs
or promised-mongo, could you tell me the versions you are using for each of
these?


Reply to this email directly or view it on GitHub
<https://github.com/gordonmleigh/promised-mongo/issues/22#issuecomment-11512
0966> .

**Comment by gordonmleigh** [comment]
Yes you need a database server running so that it has something to run the tests against.  The tests assume you have a local mongo instance.  

You're using an old version of promised-mongo, is it feasible to upgrade?  The passing test I wrote for you is for the current version 1.1.1.

**Comment by StJohn3D** [comment]
Thanks, and yes I was wrong, we are using 1.1.1

I ran the test and it passed. There was just one test so I hope that¹s
right.

Are you sure you didn¹t see anything wrong with our code?

Thanks,
St. John

From:  Gordon Mackenzie-Leigh <notifications@github.com>
Reply-To:  gordonmleigh/promised-mongo
<reply+0073aeff0c80afd42d2f362ab044b96d9fdfb7053bf49ddb92cf0000000111a3cc439
2a169ce0567b69c@reply.github.com>
Date:  Thursday, June 25, 2015 at 10:03 AM
To:  gordonmleigh/promised-mongo <promised-mongo@noreply.github.com>
Cc:  "St. John Peaster" <stjohn3d@outlook.com>
Subject:  Re: [promised-mongo] Index weights are not being applied (#22)


Yes you need a database server running so that it has something to run the
tests against.  The tests assume you have a local mongo instance.

You're using an old version of promised-mongo, is it feasible to upgrade?
The passing test I wrote for you is for the current version 1.1.1.


Reply to this email directly or view it on GitHub
<https://github.com/gordonmleigh/promised-mongo/issues/22#issuecomment-11526
8798> .

**Comment by gordonmleigh** [comment]
The `--grep` option means it will only run that test.  My test pretty much uses the code you provided (see [test/Collection.js](https://github.com/gordonmleigh/promised-mongo/blob/1.1.2/test/Collection.js#L64).  Since the test is passing, it must be working.

**Comment by StJohn3D** [comment]
Well thanks for your help. We¹ll do some more experimentation. We are
running mongodb in a docker container but it¹s supposed to be the latest
version.

From:  Gordon Mackenzie-Leigh <notifications@github.com>
Reply-To:  gordonmleigh/promised-mongo
<reply+0073aeff26320be35e60e7e9b2add518749c72c420af220292cf0000000111abc8b89
2a169ce0567b69c@reply.github.com>
Date:  Wednesday, July 1, 2015 at 11:26 AM
To:  gordonmleigh/promised-mongo <promised-mongo@noreply.github.com>
Cc:  "St. John Peaster" <stjohn3d@outlook.com>
Subject:  Re: [promised-mongo] Index weights are not being applied (#22)


The --grep option means it will only run that test.  My test pretty much
uses the code you provided (see test/Collection.js
<https://github.com/gordonmleigh/promised-mongo/blob/1.1.2/test/Collection.j
s#L64> .  Since the test is passing, it must be working.


Reply to this email directly or view it on GitHub
<https://github.com/gordonmleigh/promised-mongo/issues/22#issuecomment-11771
4922> .

**Comment by gordonmleigh** [comment]
Ok I'll close this issue just now then, though I can reopen if you get any more info.

**Comment by StJohn3D** [comment]
Thanks

From:  Gordon Mackenzie-Leigh notifications@github.com
Reply-To:  gordonmleigh/promised-mongo
<reply+0073aeff11da8e72f03760d2721f7e7701be2737f5a67de392cf0000000111aca5c99
2a169ce0567b69c@reply.github.com>
Date:  Thursday, July 2, 2015 at 3:10 AM
To:  gordonmleigh/promised-mongo promised-mongo@noreply.github.com
Cc:  "St. John Peaster" stjohn3d@outlook.com
Subject:  Re: [promised-mongo] Index weights are not being applied (#22)

Ok I'll close this issue just now then, though I can reopen if you get any
more info.


Reply to this email directly or view it on GitHub
<https://github.com/gordonmleigh/promised-mongo/issues/22#issuecomment-11793
7522> .
