### ISSUE TITLE
Update doesn't throw exceptions

### ISSUE THREAD

**Issue by stewartml** [gordonmleigh/promised-mongo#24]
`db.collection.update` doesn't throw exceptions as expected.

Example:

    import pmongo from 'promised-mongo';
    let db = pmongo('test');
    ...
    let users = db.collection('users');
    await users.createIndex({email: 1}, {unique: true});
    await users.insert({email: 'foo@test.co.uk'});
    await users.insert({email: 'bar@test.co.uk'});
    let result = await users.update({email: 'foo@test.co.uk'}, {email: 'bar@test.co.uk'});

`result` will now be:

    { ok: 1,
      nModified: 0,
      n: 0,
      writeErrors: 
       [ { index: 0,
           code: 11000,
           errmsg: 'E11000 duplicate key error index: test.users.$email_1 dup key: { : "bar@test.co.uk" }' }],
      updatedExisting: true }

Obviously, I expected it to throw an error with a `code` field equaling `11000`.

**Comment by stewartml** [comment]
Incidentally, `insert` doesn't throw either, and there isn't even a `writeErrors` field on the result.

**Comment by gordonmleigh** [comment]
Fixed in 1.1.4.
