### ISSUE TITLE
How do I suppose to handle db connection error?

### ISSUE THREAD

**Issue by artin-phares** [gordonmleigh/promised-mongo#25]
I'm using <code>var db = pmongo(connectionString)</code> to connect to database.

Recently I've noticed that there's no exception when my database is off.
Calls to db object just stuck on <code>yield db.collection(XXX)</code>

How do I suppose to handle db connection error?

**Comment by gordonmleigh** [comment]
I'm working on this, will have a fix shortly!

**Comment by gordonmleigh** [comment]
Fixed in 1.1.4!

You will need to add an extra options parameter to the `pmongo` function:

    db = pmongo('mongodb://invaliddomain/', {emitError: true, reconnect: false})

The `emitError` parameter is required for errors to be thrown (this gets passed down the `mongodb-core` api) and you need to turn off auto-reconnect so that it will throw an error instead of continuing to try to connect.

**Comment by art-in** [comment]
Thanks. Now it throws errors.

...not on db init, but when actually using db later.
I need it to die as soon as possible.

Does this helper look good?

``` javascript
var db = connect('mongodb://invaliddomain/');

function connect(connectionString) {
  var db = pmongo(connectionString, {emitError: true, reconnect: false});

  // Test connection
  db.collection('test_connection')
    .find()
    .toArray()
    .catch(function(e) {
      console.log(e);
      process.exit(1);
    });

  return db;
}
```

**Comment by gordonmleigh** [comment]
You can call `db.connect()` to connect immediately.  This will return a promise that you can wait on:

```
var db = connect('mongodb://invaliddomain/');

function connect(connectionString) {
  var db = pmongo(connectionString, {emitError: true, reconnect: false});

  // Test connection
  db.connect()
    .catch(function(e) {
      console.log(e);
      process.exit(1);
    });

  return db;
}
```

**Comment by art-in** [comment]
Nice. Thanks.
