### ISSUE TITLE
add support to finally()

### ISSUE THREAD

**Issue by haoliangyu** [gordonmleigh/promised-mongo#48]
It would be nice to add support to `finally()` function for performing cleaning task.

`db.collection(...).find(...).then(...).catch(...).finally(..)`

I tried to use it but got a error of no `finally` function.

**Comment by grrowl** [comment]
FWIW, it's not implemented in native Promises, which this library would use under the hood: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise
