### ISSUE TITLE
How to set server options?

### ISSUE THREAD

**Issue by ashleydavis** [gordonmleigh/promised-mongo#8]
Hi Gordon, love your work.

Is there any way to set server options as specified here:
http://mongodb.github.io/node-mongodb-native/api-generated/server.html#server

Specifically I want to enable 'auto_reconnect'.

Ta

**Comment by kmiyashiro** [comment]
`auto_reconnect` is true by default using mongojs I believe.

**Comment by gordonmleigh** [comment]
I can confirm that this is set by default for you - it passes `options.reconnect = true` in [lib/Database.js](https://github.com/gordonmleigh/promised-mongo/blob/1.1.1/lib/Database.js#L93) - not sure why the name differs from the mongodb-native library but a quick scan of mongodb-core (which I use) suggests that `reconnect` is the right value.
